### ISSUE TITLE
メールサーバが無いためテストが通らない

### ISSUE THREAD

**Issue by hoshitocat** [hoshitocat/jpmobile#3]
### エラー内容

```
Failure/Error: expect {
       expected no Exception, got #<Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25> with backtrace:
         # ./vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
         # ./vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
         # ./vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
         # ./spec/unit/mail_spec.rb:347:in `block (4 levels) in <top (required)>'
         # ./spec/unit/mail_spec.rb:346:in `block (3 levels) in <top (required)>'
```

**Comment by hoshitocat** [comment]
### メソッドのモックを作成する

実際の送信処理は、ActionMailerが使われているためテストの本質ではない。したがって、このメソッドのモックを作成することで解決
